import { createVoxelGrid, setVoxel } from '../voxel/voxelGrid';
import { encodeBlockstateKey } from './blockstateKey';
import type { ParsedStructure } from './common';

/**
 * Structures the jar doesn't ship as a file. A stronghold is generated by Java code
 * (StrongholdPieces), not loaded from a template, so there is no `.nbt` to read — the portal room is
 * built here from its real layout instead, as a `ParsedStructure` (the same shape both file parsers
 * produce), so it flows through the ordinary structure pipeline unchanged.
 *
 * The layout is transcribed layer by layer from the Minecraft Wiki's portal-room blueprint
 * (https://minecraft.wiki/w/Stronghold/Structure/Portal_Room) and cross-checked against the wiki's
 * own block counts: 15 lava, 39 iron bars, 12 end portal frames, one silverfish spawner. The wiki
 * also has 8 stone-brick stairs (three rising steps up to the spawner); per explicit request only
 * the bottom row of 3 is kept, so the upper two rows (y=2 and y=3) are left out. Text row 0 is the back wall (z=15); the last row is the entrance wall (z=0).
 *
 * Two versions, `eyes: false` (every frame empty) and `eyes: true` (all 12 filled). Filling all 12
 * is exactly what opens the portal in the game, so the eyes version also fills the 3x3 centre with
 * `end_portal`.
 *
 * The game varies the wall blocks randomly (stone / mossy / cracked, the infested stone bricks
 * hiding the silverfish aside); a fixed-seed generator reproduces that mix, so the same build always
 * looks the same.
 */

const SIZE_X = 11;
const SIZE_Y = 8;
const SIZE_Z = 16;

const LAYERS: string[][] = [
  // y=0 — the floor, solid
  Array(16).fill('SSSSSSSSSSS'),
  // y=1
  [
    'SSSSSSSSSSS',
    'S         S',
    'S         S',
    'S  SSSSS  S',
    'S  SLLLS  S',
    'S  SLLLS  S',
    'S  SLLLS  S',
    'S  SSSSS  S',
    'S   SSS   S',
    'S   SSS   S',
    'S   SSS   S',
    'SSS TTT SSS',
    'SLS     SLS',
    'SLS     SLS',
    'SLS     SLS',
    'SSSSI ISSSS',
  ],
  // y=2
  [
    'SSSSSSSSSSS',
    'S         S',
    'S         S',
    'S         S',
    'S         S',
    'S         S',
    'S         S',
    'S         S',
    'S   SSS   S',
    'S   SSS   S',
    'S         S',
    'S         S',
    'S         S',
    'S         S',
    'S         S',
    'SSSSI ISSSS',
  ],
  // y=3 — the frame ring
  [
    'SSISISISISS',
    'S         S',
    'I         I',
    'S   EEE   S',
    'I  E   E  I',
    'S  E   E  S',
    'I  E   E  I',
    'S   EEE   S',
    'I   SSS   I',
    'S    s    S',
    'I         I',
    'S         S',
    'I         I',
    'S         S',
    'S         S',
    'SSSSIIISSSS',
  ],
  // y=4
  [
    'SSISISISISS',
    'S         S',
    'I         I',
    'S         S',
    'I         I',
    'S         S',
    'I         I',
    'S         S',
    'I         I',
    'S         S',
    'I         I',
    'S         S',
    'I         I',
    'S         S',
    'S         S',
    'SSSSSSSSSSS',
  ],
  // y=5
  ['SSSSSSSSSSS', ...Array(14).fill('S         S'), 'SSSSSSSSSSS'],
  // y=6 — the lowered ceiling edge
  [
    'SSSSSSSSSSS',
    'SSSSSSSSSSS',
    ...Array(11).fill('SS       SS'),
    'SSSSSSSSSSS',
    'SSSSSSSSSSS',
    'SSSSSSSSSSS',
  ],
  // y=7 — the roof
  Array(16).fill('SSSSSSSSSSS'),
];

const STAIRS = encodeBlockstateKey('minecraft:stone_brick_stairs', { facing: 'north', half: 'bottom', shape: 'straight', waterlogged: 'false' });
const LAVA = encodeBlockstateKey('minecraft:lava', { level: '0' });

/** A frame's `facing` points away from the portal centre (the side a player stands on to fill it). */
function frameKey(x: number, z: number, eye: boolean): string {
  const facing = z === 8 ? 'north' : z === 12 ? 'south' : x === 3 ? 'west' : 'east';
  return encodeBlockstateKey('minecraft:end_portal_frame', { eye: String(eye), facing });
}

// mulberry32 — a tiny seeded PRNG so the random wall mix is the same on every build.
function seededRandom(seed: number): () => number {
  let a = seed;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** The game's stone-brick mix for a stronghold wall: ~20% cracked, ~30% mossy, the rest plain. */
function wallBlock(random: () => number): string {
  const r = random();
  if (r < 0.2) return 'minecraft:cracked_stone_bricks';
  if (r < 0.5) return 'minecraft:mossy_stone_bricks';
  return 'minecraft:stone_bricks';
}

function buildPortalRoom(eyes: boolean): ParsedStructure {
  const grid = createVoxelGrid(SIZE_X, SIZE_Y, SIZE_Z);
  const blockIds = new Set<string>();
  const random = seededRandom(0x57406e6);

  const cells = new Map<string, string>();
  const at = (x: number, y: number, z: number) => `${x},${y},${z}`;
  const put = (x: number, y: number, z: number, id: string) => cells.set(at(x, y, z), id);

  LAYERS.forEach((rows, y) => {
    rows.forEach((row, r) => {
      const z = SIZE_Z - 1 - r;
      for (let x = 0; x < SIZE_X; x++) {
        const ch = row[x];
        if (ch === ' ') continue;
        if (ch === 'S') put(x, y, z, wallBlock(random));
        else if (ch === 'L') put(x, y, z, LAVA);
        else if (ch === 'T') put(x, y, z, STAIRS);
        else if (ch === 'I') put(x, y, z, 'minecraft:iron_bars');
        else if (ch === 'E') put(x, y, z, frameKey(x, z, eyes));
        else if (ch === 's') put(x, y, z, 'minecraft:spawner');
      }
    });
  });

  if (eyes) {
    for (let x = 4; x <= 6; x++) for (let z = 9; z <= 11; z++) put(x, 3, z, 'minecraft:end_portal');
  }

  // Iron bars join a neighbouring bar or a solid wall block, exactly as the game connects them.
  const connectsTo = (id: string | undefined) => id !== undefined && (id === 'minecraft:iron_bars' || id.endsWith('stone_bricks'));
  for (const [key, id] of [...cells]) {
    if (id !== 'minecraft:iron_bars') continue;
    const [x, y, z] = key.split(',').map(Number);
    cells.set(
      key,
      encodeBlockstateKey('minecraft:iron_bars', {
        north: String(connectsTo(cells.get(at(x, y, z - 1)))),
        south: String(connectsTo(cells.get(at(x, y, z + 1)))),
        east: String(connectsTo(cells.get(at(x + 1, y, z)))),
        west: String(connectsTo(cells.get(at(x - 1, y, z)))),
        waterlogged: 'false',
      })
    );
  }

  for (const [key, id] of cells) {
    const [x, y, z] = key.split(',').map(Number);
    setVoxel(grid, x, y, z, id);
    blockIds.add(id);
  }
  return { grid, blockIds };
}

const GENERATORS: Record<string, () => ParsedStructure> = {
  'stronghold/portal_room': () => buildPortalRoom(false),
  'stronghold/portal_room_with_eyes': () => buildPortalRoom(true),
};

export const GENERATED_STRUCTURE_NAMES = Object.keys(GENERATORS);

export function generateStructure(name: string): ParsedStructure | null {
  return GENERATORS[name]?.() ?? null;
}
